export const sampleStamps = [
  {
    id: '1',
    name: 'Penny Black',
    purchase_date: new Date('1840-05-01'),
    purchase_price: 150.0,
    seller: 'Stanley Gibbons',
    currency: 'GBP',
    valuation: 3000.0,
    image_url: '/stamps/penny-black.jpg',
    is_sold: false,
  },
  {
    id: '2',
    name: 'Inverted Jenny',
    purchase_date: new Date('1918-05-14'),
    purchase_price: 200000.0,
    seller: 'Private Auction',
    currency: 'USD',
    valuation: 1600000.0,
    image_url: '/stamps/inverted-jenny.jpg',
    is_sold: false,
  },
  {
    id: '3',
    name: 'Mauritius \"Post Office\"',
    purchase_date: new Date('1847-09-20'),
    purchase_price: 50000.0,
    seller: 'David Feldman SA',
    currency: 'CHF',
    valuation: 4000000.0,
    image_url: '/stamps/mauritius.jpg',
    is_sold: true,
  },
    {
    id: '4',
    name: 'British Guiana 1c Magenta',
    purchase_date: new Date('1856-04-04'),
    purchase_price: 1000000.0,
    seller: 'Sotheby\'s',
    currency: 'USD',
    valuation: 9480000.0,
    image_url: '/stamps/guiana-magenta.jpg',
    is_sold: false,
  },
  {
    id: '5',
    name: 'Treskilling Yellow',
    purchase_date: new Date('1855-07-01'),
    purchase_price: 80000.0,
    seller: 'Auction House',
    currency: 'SEK',
    valuation: 2300000.0,
    image_url: '/stamps/treskilling-yellow.jpg',
    is_sold: false,
  },
];
