import { createClient } from "@/lib/supabase/server";
import { cookies } from "next/headers";
import type { Metadata } from "next";
import { Toaster } from "@/components/ui/sonner";
import { Header } from "@/components/layout/Header";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const supabase = createClient(cookieStore);
  const { data: { user } } = await supabase.auth.getUser();

  return (
    <html lang="en">
      <body
        className={"font-sans antialiased"}
      >
        <Header user={user} />
        {children}
        <Toaster />
      </body>
    </html>
  );
}
